version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: streamlit_app
    container_name: streamlit_app
    env_file:
      - .env_app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8501:8501"
    volumes:
      - ./temp_files:/app/temp_files
      - ./processed_files:/app/processed_files
    depends_on:
      - worker
      - redis
    networks:
      - app_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    image: celery_worker
    container_name: celery_worker
    env_file:
      - .env_app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./temp_files:/app/temp_files
      - ./processed_files:/app/processed_files
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile_flower
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env_app
    image: celery_flower
    container_name: celery_flower
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
