# Dockerfile_app
FROM python:3.12-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo requirements.txt e instalar as dependências
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação
COPY app.py /app/
COPY tasks.py /app/
COPY pages/ /app/pages/
COPY app_utils /app/app_utils
COPY glpi_client/ /app/glpi_client
# Criar o diretório para arquivos temporários
RUN mkdir -p /app/temp_files

# Expor a porta padrão do Streamlit
EXPOSE 8501

# Comando para executar a aplicação
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false", "--browser.gatherUsageStats=false"]
