# Dockerfile_worker
FROM python:3.12-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo requirements.txt e instalar as dependências
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação
COPY tasks.py /app/
COPY glpi_client/ /app/glpi_client
# Criar o diretório para arquivos temporários
RUN mkdir -p /app/temp_files

# Comando para executar o worker do Celery
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=2"]
